SIDEBAR_EXPANDED_WIDTH = 220
SIDEBAR_COLLAPSED_WIDTH = 56
SIDEBAR_COLLAPSE_THRESHOLD = 1100

TITLE_BAR_HEIGHT = 44
STATUS_BAR_HEIGHT = 28

DEFAULT_WINDOW_WIDTH = 1440
DEFAULT_WINDOW_HEIGHT = 860
MIN_WINDOW_WIDTH = 1100
MIN_WINDOW_HEIGHT = 700

PREVIEW_MIN_WIDTH = 500
PREVIEW_PLACEHOLDER_MIN_WIDTH = 400
PREVIEW_PLACEHOLDER_MIN_HEIGHT = 500
PREVIEW_LABEL_MIN_WIDTH = 350
PREVIEW_LABEL_MIN_HEIGHT = 500

THUMBNAIL_LIST_WIDTH = 80
THUMBNAIL_ITEM_HEIGHT = 110
THUMBNAIL_SCALE = 0.5

NAV_BAR_HEIGHT = 40
NAV_BUTTON_SIZE = 36
NAV_BUTTON_HEIGHT = 30

SIDEBAR_ITEM_HEIGHT = 44
SIDEBAR_MARGIN = 8
SIDEBAR_SPACING = 4

FEATURE_CARD_WIDTH = 260
FEATURE_CARD_HEIGHT = 160

MAX_RENDER_ZOOM = 4.0
MIN_LABEL_SIZE = 10

PATH_TRUNCATE_MAX_LEN = 30

PAGE_ANIM_OUT_DURATION = 100
PAGE_ANIM_IN_DURATION = 150

THEME_NAMES = ('minimal', 'ink', 'scifi')
DEFAULT_THEME = 'minimal'

EXPORT_DIR_NAME = 'PDFTool_Output'
